- name: "installing nginx"
  hosts: localhost
  become: true
  tasks:
    - name: "nginx installation"
      ansible.builtin.package:
        - name: "nginx"
          state: installed

    - name: "starting the nginx"
      ansible.builtin.service:
        - name: "nginx"
          state: "started"
          enabled: yes
          
