- name: "Inventory variables"
  hosts: "local"
  connection: "local"
  tasks: 
    - name: "msg with inventory variables"
      ansible.builtin.debug:
        msg: "Hello {{ course }}, the course duration is {{ duration }} and the trainer is {{ trainer }}."