[local]
localhost ansible_connection=local

[frontend]
172.31.70.39 ansible_connection=ssh ansible_user=ec2-user ansible_password=DevOps321

[local:vars]
course= "Devops with both AWS and Azure"
duration= "19HRS"
trainer= "Siva kumar and Prasanth"